export const SELECTED_EMPLOYEE_CODE = 'SELECTED_EMPLOYEE_CODE';
export const LIST_EMPLOYEE = 'LIST_EMPLOYEE';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const REMOVE_EMPLOYEE = 'REMOVE_EMPLOYEE';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
